---
name: Galaxy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy Collection
        uses: docker://buluma/ansible_galaxy_collection:latest
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
